#-*- coding=utf-8-*-
import sys
reload(sys)
sys.setdefaultencoding( "utf-8" )
a = 5
b = 5
print a is b # True
a = 500
b = 500
print a is b # False

s = 'dasda'
print s[1:3]
print s.startswith('das')

dalei = [
    u'建筑工程',
    u'财会经济',
    u'医学卫生',
    u'外语考试',
    u'职业资格',
    u'学历教育',
    u'计算机考试'
]
xiaolei = {
            u'一级建造师':u'一级建造师',
            u'二级建造师':u'二级建造师',
            u'监理工程师':u'监理工程师',
            u'咨询工程师':u'咨询工程师',
            u'造价工程师':u'造价工程师',
            u'结构工程师':u'结构工程师',
            u'电气工程师':u'电气工程师',
            u'物业管理师':u'物业管理师',
            u'经济师':u'经济师',
            u'设计师':u'设计师',
            u'初级会计':u'初级会计师',
            u'中级会计师':u'中级会计师',
            u'注册会计师':u'注册会计师',
            u'统计师':u'统计师',
            u'审计师':u'审计师',
            u'注册税务师':u'注册税务师',
            u'执业药师':u'执业药师',
            u'执业药师':u'执业药师',
            u'执业护士':u'执业护士',
            u'临床执业':u'临床执业',
            u'中西医执业':u'中西医执业',
            u'中医执业':u'中医执业',
            u'主治':u'主治',
            u'检验':u'检验',
            u'英语四级':u'英语四六级',
            u'英语六级':u'英语四六级',
            u'雅思':u'雅思',
            u'托福':u'托福',
            u'GRE考试':u'GRE考试',
            u'职称英语':u'职称英语',
            u'公共英语':u'公共英语',
            u'商务英语':u'商务英语',
            u'日语':u'日语',
            u'人力资源':u'人力资源',
            u'心理咨询师':u'心理咨询师',
            u'物流师':u'物流师',
            u'公共营养师':u'公共营养师',
            u'秘书资格':u'秘书资格',
            u'证券经纪人':u'证券经纪人',
            u'电子商务':u'电子商务',
            u'国家司法':u'国家司法',
            u'成人高考':u'成人高考',
            u'自考':u'自考',
            u'MBA':u'MBA',
            u'法律硕士':u'法律硕士',
            u'会计硕士':u'会计硕士',
            u'工程硕士':u'工程硕士',
            u'MPA':u'公共硕士',
            u'考研':u'考研',
            u'计算机等级':u'计算机等级',
            u'软件水平':u'软件水平',
            u'微软认证':u'微软认证',
            u'Cisco认证':u'Cisco认证',
            u'Oracle认证':u'Oracle认证',
            u'职称计算机':u'职称计算机',
            u'Java认证':u'Java认证',
            u'华为认证':u'华为认证',
    }

xiaolei = {
    u'一级建造师': u'一级建造师',
    u'二级建造师': u'二级建造师',
    u'监理工程师': u'监理工程师',
    u'咨询工程师': u'咨询工程师',
    u'造价工程师': u'造价工程师',
    u'结构工程师': u'结构工程师',
    u'电气工程师': u'电气工程师',
    u'物业管理师': u'物业管理师',
    u'经济师': u'经济师',
    u'设计师': u'设计师',
    u'初级会计职称': u'初级会计师',
    u'会计从业证': u'初级会计师',
    u'中级会计师': u'中级会计师',
    u'注册会计师': u'注册会计师',
    u'统计师': u'统计师',
    u'审计师': u'审计师',
    u'注册税务师': u'注册税务师',
    u'执业药师': u'执业药师',
    u'护士资格': u'执业护士',
    u'临床执业医师': u'临床执业',
    u'中西医执业医师': u'中西医执业',
    u'中医执业医师': u'中医执业',
    u'主治': u'主治',
    u'检验': u'检验',
    u'英语四级': u'英语四六级',
    u'英语六级': u'英语四六级',
    u'雅思': u'雅思',
    u'托福': u'托福',
    u'GRE考试': u'GRE考试',
    u'职称英语': u'职称英语',
    u'公共英语': u'公共英语',
    u'商务英语': u'商务英语',
    u'日语': u'日语',
    u'人力资源': u'人力资源',
    u'心理咨询师': u'心理咨询师',
    u'物流师': u'物流师',
    u'公共营养师': u'公共营养师',
    u'秘书资格': u'秘书资格',
    u'证券经纪人': u'证券经纪人',
    u'电子商务': u'电子商务',
    u'国家司法': u'国家司法',
    u'成人高考': u'成人高考',
    u'自考': u'自考',
    u'MBA': u'MBA',
    u'法律硕士': u'法律硕士',
    u'会计硕士': u'会计硕士',
    u'工程硕士': u'工程硕士',
    u'MPA': u'公共硕士',
    u'考研': u'考研',
    u'计算机等级': u'计算机等级',
    u'软件水平': u'软件水平',
    u'微软认证': u'微软认证',
    u'Cisco认证': u'Cisco认证',
    u'Oracle认证': u'Oracle认证',
    u'职称计算机': u'职称计算机',
    u'Java认证': u'Java认证',
    u'华为认证': u'华为认证',
}

da_xiao_lei = {
    u'一级建造师':u'建筑工程',
    u'二级建造师':u'建筑工程',
    u'消防工程师':u'建筑工程',
    u'护士资格':u'医学卫生',
    u'初级护师':u'医学卫生',
    u'主管护师':u'医学卫生',
    u'临床执业医师':u'医学卫生',
    u'临床助理医师':u'医学卫生',
    u'中医执业医师':u'医学卫生',
    u'中医助理医师':u'医学卫生',
    u'中西医执业医师':u'医学卫生',
    u'中西医助理医师':u'医学卫生',
    u'执业药师':u'医学卫生',
    u'会计从业证':u'财会经济',
    u'初级会计职称':u'财会经济',
    u'银行从业':u'财会经济',
    u'证券从业':u'财会经济',
    u'基金从业':u'财会经济',

}

type_dict = {
    u'执业医师':[u'医学卫生',u'执业医师'],
    u'':[u'医学卫生',u'执业药师'],
    u'临床医师':[u'医学卫生',u'临床执业'],
    u'中医医师':[u'医学卫生',u'中医执业'],
    u'中西医医师':[u'医学卫生',u'中西医执业'],
    u'中医助理':[u'医学卫生',u'中医助理'],
    u'中西医助理':[u'医学卫生',u'中西医助理'],
    u'':[u'医学卫生',u'主治'],
    u'':[u'医学卫生',u'检验'],
    u'':[u'医学卫生',u'执业护士'],


    u'':[u'学历教育',u'成人高考'],
    u'':[u'学历教育',u'自考'],
    u'':[u'学历教育',u'MBA'],
    u'':[u'学历教育',u'法律硕士'],
    u'':[u'学历教育',u'会计硕士'],
    u'':[u'学历教育',u'工程硕士'],
    u'':[u'学历教育',u'公共硕士'],
    u'':[u'学历教育',u'考研'],

    u'':[u'计算机考试',u'计算机等级'],
    u'':[u'计算机考试',u'软件水平'],
    u'':[u'计算机考试',u'微软认证'],
    u'':[u'计算机考试',u'Cisco认证'],
    u'':[u'计算机考试',u'Oracle认证'],
    u'':[u'计算机考试',u'职称计算机'],
    u'':[u'计算机考试',u'Java认证'],
    u'':[u'计算机考试',u'华为认证'],
    u'':[u'计算机考试',u'Linux认证'],

}

key_url =[
    'http://chuji.dongao.com/zchjsdh/kstk/mryl/',
    'http://chuji.dongao.com/zchjsdh/kstk/lnzt/',
    'http://chuji.dongao.com/zchjsdh/kstk/tblx/',
    'http://chuji.dongao.com/zchjsdh/kstk/mnst/',
    'http://zhongji.dongao.com/ghzcdh/kstk/lnzt/',
    'http://zhongji.dongao.com/ghzcdh/kstk/mryl/',
    'http://zhongji.dongao.com/ghzcdh/kstk/tblx/',
    'http://shuiwushi.dongao.com/taxdh/kstk/lnzt/',
    'http://shuiwushi.dongao.com/taxdh/kstk/mryl/',
    'http://shuiwushi.dongao.com/taxdh/kstk/tblx/',
    'http://zhukuai.dongao.com/zchjsdh/kstk/lnzt/',
    'http://zhukuai.dongao.com/zchjsdh/kstk/mryl/',
    'http://zhukuai.dongao.com/zchjsdh/kstk/tblx/',
    'http://gaoji.dongao.com/ghzcdh/kstk/lnzt/',
    'http://gaoji.dongao.com/ghzcdh/kstk/mryl/',
    'http://congye.dongao.com/qg/kstk/lnzt/',
    'http://congye.dongao.com/qg/kstk/mryl/',
    'http://congye.dongao.com/qg/kstk/mnks/',
]